const auctions = {
  categoryName: 'auctions',

  categoryInfo: {
    imageUrl: '/images/digital/headphone-1.png',
    color: 'darkblue',
  },
  products: [
    {
      id: 9,
      name: 'asus gaming',
      price: 4567,
      details: 'high-performance gaming.',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 9,
      firstImage: '/images/computer/case2.png',
      hoverImage: '/images/computer/case1.png',
    },
   { id: 2,
    name: 'iphone 15 pro max',
    price: 1525,
    details: 'good iphone 14 pro max',
    isInWishlist: false,
    isInCart: false,
    isInCompare: false,
    isInAuctions: false,
    count: 8,
    firstImage: '/images/phone/phone7.jpg',
    hoverImage: '/images/phone/phone1.jpg',
},

    {
      id: 5,
      name: 'lenovo core i3',
      price: 4343,
      details: 'gaming',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 13,
      firstImage: '/images/laptop/laptop1.jpg',
      hoverImage: '/images/laptop/laptop4.jpg',
    },
    {
      id: 17,
      name: 'apple watch',
      price: 1268,
      details: 'goood',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 7,
      firstImage: '/images/watch/watch3.png',
      hoverImage:'/images/watch/watch2.png',
    },
    {
      id: 21,
      categoryName: 'accessories',
      name: 'headphone',
      price: 569,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 4,
      firstImage: '/images/headphone/headphone4.jpg',
      hoverImage: '/images/headphone/headphone3.png',
    },
  ],
};

const phones = {
  categoryName: 'phones',
  categoryInfo: {
    title: 'Phones',
    imageUrl: '/images/phone/phone5.png',
    color: 'blue',
  },
  products: [
    {
      id: 1,
      name: 'iphone 16 pro max',
      price: 1929,
      details: 'perfect',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 8,
      firstImage: '/images/phone/phone1.jpg',
      hoverImage: '/images/phone/phone6.jpg',
    },
    {
      id: 2,
      name: 'iphone 15 pro max',
      price: 1525,
      details: 'good iphone 14 pro max',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 8,
      firstImage: '/images/phone/phone7.jpg',
      hoverImage: '/images/phone/phone1.jpg',
    },

    {
      id: 3,
      name: 'iphone 14 pro max',
      price: 1268,
      details: 'good iphone 14 pro max',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 5,
      firstImage: '/images/phone/phone6.jpg',
      hoverImage: '/images/phone/phone8.jpg',
    },

    {
      id: 4,
      name: 'iphone 13 pro max',
      price: 1019,
      details: 'good iphone 14 pro max',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 2,
      firstImage: '/images/phone/phone8.jpg',
      hoverImage: '/images/phone/phone1.jpg',
    },
  ],
};
const laptops = {
  categoryName: 'laptops',

  categoryInfo: {
    title: 'Laptops',
    imageUrl: '/images/laptop/laptop1.png',
    color: 'orange',
  },
  products: [
    {
      id: 5,
      name: 'lenovo core i3',
      price: 4343,
      details: 'gaming',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 13,
      firstImage: '/images/laptop/laptop1.jpg',
      hoverImage: '/images/laptop/laptop4.jpg',
    },
    {
      id: 6,
      name: 'lenovo cor i5',
      price: 334,
      details: 'programming',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 8,
      firstImage: '/images/laptop/laptop2.jpg',
      hoverImage: '/images/laptop/laptop3.jpg',
    },
    {
      id: 7,
      name: 'lenovo cor i5',
      price: 334,
      details: 'programming',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 5,
      firstImage: '/images/laptop/laptop4.jpg',
      hoverImage: '/images/laptop/laptop5.jpg',
    },
    {
      id: 8,
      name: 'lenovo cor i5',
      price: 334,
      details: 'programming',
      isInWishlist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 7,
      firstImage: '/images/laptop/laptop6.jpg',
      hoverImage: '/images/laptop/laptop7.jpg',
    },
  ],
};

const computers = {
  categoryName: 'computers',
  categoryInfo: {
    title: 'computers',
    imageUrl: '/images/computer/case2.png',
    color: 'orangered',
  },

  products: [
    {
      id: 9,
      name: 'asus gaming',
      price: 4567,
      details: 'high-performance gaming.',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 9,
      firstImage: '/images/computer/case2.png',
      hoverImage: '/images/computer/case1.png',
    },
    {
      id: 10,
      name: 'x power',
      price: 1567,
      details: ' best-performance ',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 10,
      firstImage: '/images/computer/case3.png',
      hoverImage: '/images/computer/case6.png',
    },
    {
      id: 11,
      name: 'green gaming',
      price: 1500,
      details: 'powerfull',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 12,
      firstImage: '/images/computer/case8.png',
      hoverImage: '/images/computer/case9.png',
    },
    {
      id: 12,
      name: 'apple',
      price: 2564,
      details: 'high-performance ',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 4,
      firstImage: '/images/computer/case10.png',
      hoverImage: '/images/computer/case11.png',
    },
    {
      id: 13,
      name: 'asus',
      price: 3800,
      details: 'progaming',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 5,
      firstImage: '/images/computer/case12.png',
      hoverImage: '/images/computer/case13.png',
    },
    {
      id: 14,
      name: 'gaming pro',
      price: 1554,
      details: ' high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 17,
      firstImage: '/images/computer/case16.png',
      hoverImage: '/images/computer/case15.png',
    },
    {
      id: 15,
      name: 'best case',
      price: 1554,
      details: 'web development',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 18,
      firstImage: '/images/computer/case17.png',
      hoverImage: '/images/computer/case20.png',
    },
    {
      id: 16,
      name: 'best case',
      price: 1554,
      details: 'for front-end devlopers',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 10,
      firstImage: '/images/computer/case18.png',
      hoverImage: '/images/computer/case19.png',
    },
  ],
};
const watches = {
  categoryName: 'watches',
  categoryInfo: {
    imageUrl: '/images/watch/watch3.png',
    color: 'purple',
  },
  products: [
    {
      id: 17,
      name: 'apple watch',
      price: 1268,
      details: 'goood',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 7,
      firstImage: '/images/watch/watch3.png',
      hoverImage:'/images/watch/watch2.png',
    },
    {
      id: 18,
      name: 'apple watch pro',
      price: 1065,
      details: 'goood',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 7,
      firstImage: '/images/watch/watch2.png',
      hoverImage:'/images/watch/watch3.png',
    },
    {
      id: 19,
      name: 'watch pro max',
      price: 1921,
      details: 'goood',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 7,
      firstImage: '/images/watch/watch1.png',
      hoverImage:'/images/watch/watch2.png',
    },
  ],
};

const accessories = {
  categoryName: 'headphones',

  categoryInfo: {
    imageUrl: '/images/headphone/headphone3.png',
    color: 'indigo',
  },
  products: [
    {
      id: 20,
      categoryName: 'headphones',
      name: 'headphone',
      price: 156,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 7,
      firstImage: '/images/headphone/headphone1.jpg',
      hoverImage: '/images/headphone/headphone7.jpg',
    },
    {
      id: 21,
      categoryName: 'accessories',
      name: 'headphone',
      price: 569,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 4,
      firstImage: '/images/headphone/headphone2.jpg',
      hoverImage: '/images/headphone/headphone4.jpg',
    },
    {
      id: 22,
      categoryName: 'accessories',
      name: 'zgh 244',
      price: 157,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 26,
      firstImage: '/images/headphone/headphone4.jpg',
      hoverImage: '/images/headphone/headphone3.png',
    },
    {
      id: 23,
      categoryName: 'accessories',
      name: 'x 864',
      price: 356,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 2,
      firstImage: '/images/headphone/headphone6.jpg',
      hoverImage: '/images/headphone/headphone7.jpg',
    },
    {
      id: 24,
      categoryName: 'accessories',
      name: 'headphone ax',
      price: 454,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 24,
      firstImage: '/images/headphone/headphone8.jpg',
      hoverImage: '/images/headphone/headphone9.jpg',
    },
    {
      id: 24,
      categoryName: 'accessories',
      name: 'headphone 454',
      price: 454,
      details: 'high-quality',
      isInWahslist: false,
      isInCart: false,
      isInCompare: false,
      isInAuctions: false,
      count: 24,
      firstImage: '/images/headphone/headphone7.jpg',
      hoverImage: '/images/headphone/headphone2.jpg',
    },
  ],
};

const allCategoriesData = [
  phones,
  laptops,
  watches,
  accessories,
  computers,
];

export {
  phones,
  laptops,
  watches,
  accessories,
  computers,
  auctions,
  allCategoriesData,
};
